name: Run tests on branch commit
on:
  push:
    branches:
      - main
      - develop
      - 2.x

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Run unit tests
    strategy:
      matrix:
        php: [ "8.0", "8.1", "8.2" ]
        phpunit: [ "9.5.10" ]

    steps:
    - uses: actions/checkout@v2

    - uses: php-actions/composer@v6

#    - name: Setup PHP runtime
#      uses: shivammathur/setup-php@v2
#      with:
#        php-version: "${{ matrix.php }}"
#        coverage: "none"

#    - name: Lint PHP files
#      run: |
#        curl -Ls https://github.com/overtrue/phplint/releases/latest/download/phplint.phar -o /usr/local/bin/phplint
#        chmod +x /usr/local/bin/phplint
#        /usr/local/bin/phplint -vvv --no-cache

    - name: PHPUnit test
      uses: php-actions/phpunit@v2
      with:
        php_version: ${{ matrix.php }}
        version: ${{ matrix.phpunit }}
        php_extensions: ldap mbstring
        configuration: phpunit.xml
        args: --coverage-text --verbose