name: Run tests on branch commit
on:
  push:
    branches:
      - main
      - develop
      - 2.x

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Run unit tests
    strategy:
      matrix:
        php: [ "8.1", "8.2", "8.3", "8.4" ]
        phpunit: [ "10.5.40" ]

    steps:
    - uses: actions/checkout@v2

    - uses: php-actions/composer@v6

    - name: Setup PHP runtime
      uses: shivammathur/setup-php@v2
      with:
        php-version: "${{ matrix.php }}"
        coverage: "none"
        tools: phplint

    - name: Lint PHP files
      run: |
        phplint -vvv --no-cache

    - name: PHPUnit test
      uses: php-actions/phpunit@v2
      with:
        php_version: ${{ matrix.php }}
        version: ${{ matrix.phpunit }}
        php_extensions: ldap mbstring
        configuration: phpunit.xml