name: Run tests on branch commit
on:
  push:
    branches:
      - main
      - develop
      - v3

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Run unit tests
    strategy:
      matrix:
        php: [ "7.4", "8.0", "8.1" ]
        phpunit: [ "9.5.10" ]

    steps:
    - uses: actions/checkout@v2

    - uses: php-actions/composer@v6

    - uses: michaelw90/PHP-Lint@master
    - run: ls -al
    - run: ls -al vendor-vendor/*
    - run: ls -al vendor-repackaged/*

    - name: PHPUnit test
      uses: php-actions/phpunit@v2
      with:
        php_version: ${{ matrix.php }}
        version: ${{ matrix.phpunit }}
        php_extensions: ldap mbstring
        configuration: phpunit.xml
        args: --coverage-text --verbose