name: Create pre-release for GitHub-only
on:
  push:
    tags-ignore:
      - '2.[0-9]+.[0-9]+'

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Run unit tests
    strategy:
      matrix:
        php: [ "8.0", "8.1" ]
        phpunit: [ "9.5.10" ]

    steps:
    - uses: actions/checkout@v2

    - uses: php-actions/composer@v6

    - uses: michaelw90/PHP-Lint@master

    - name: PHPUnit test
      uses: php-actions/phpunit@v2
      with:
        php_version: ${{ matrix.php }}
        version: ${{ matrix.phpunit }}
        php_extensions: ldap mbstring
        configuration: phpunit.xml
        args: --coverage-text --verbose

  prerelease:
    runs-on: ubuntu-latest
    needs: testing
    name: Create pre-release
    steps:
    - uses: actions/checkout@v2

    - uses: php-actions/composer@v6
      with:
        # even with a (pre-)release, we need all dev-dependencies so that strauss can repackage the namespaces.
        # we exclude the then-unnecessary vendor/ directory in the "Zip all files" step.
        dev: yes

    - name: Set environment variable
      run: echo "CURRENT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Replace NADI version string
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "REPLACE_VERSION_BY_CI"
        replace: ${{ env.CURRENT_TAG }}

    - name: Zip all files
      run: zip -r release.zip . -x ".git/*" ".github/*" -x "vendor/*"

    - name: Upload pre-release to GitHub
      uses: ncipollo/release-action@v1
      with:
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}